/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class force_pi_connector_ConnectorC */

#ifndef _Included_force_pi_connector_ConnectorC
#define _Included_force_pi_connector_ConnectorC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     force_pi_connector_ConnectorC
 * Method:    connectorFromC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_force_pi_connector_ConnectorC_connectorFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
