# TCL File Generated by Component Editor 13.0sp1
# Wed Feb 11 10:58:32 PST 2015
# DO NOT MODIFY


# 
# sad_track "sad_track" v1.0
#  2015.02.11.10:58:31
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module sad_track
# 
set_module_property DESCRIPTION ""
set_module_property NAME sad_track
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sad_track
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sad_track
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file sad_track.vhd VHDL PATH sad_track.vhd TOP_LEVEL_FILE
add_fileset_file mytypes.vhd VHDL PATH mytypes.vhd
add_fileset_file sad_block.vhd VHDL PATH sad_block.vhd
add_fileset_file sad_pixel.vhd VHDL PATH sad_pixel.vhd


# 
# parameters
# 
add_parameter pixel_buffer_base STD_LOGIC_VECTOR 0
set_parameter_property pixel_buffer_base DEFAULT_VALUE 0
set_parameter_property pixel_buffer_base DISPLAY_NAME pixel_buffer_base
set_parameter_property pixel_buffer_base WIDTH 32
set_parameter_property pixel_buffer_base TYPE STD_LOGIC_VECTOR
set_parameter_property pixel_buffer_base UNITS None
set_parameter_property pixel_buffer_base ALLOWED_RANGES 0:4294967295
set_parameter_property pixel_buffer_base HDL_PARAMETER true
add_parameter winSizeX INTEGER 20
set_parameter_property winSizeX DEFAULT_VALUE 20
set_parameter_property winSizeX DISPLAY_NAME winSizeX
set_parameter_property winSizeX TYPE INTEGER
set_parameter_property winSizeX UNITS None
set_parameter_property winSizeX ALLOWED_RANGES -2147483648:2147483647
set_parameter_property winSizeX HDL_PARAMETER true
add_parameter winSizeY INTEGER 20
set_parameter_property winSizeY DEFAULT_VALUE 20
set_parameter_property winSizeY DISPLAY_NAME winSizeY
set_parameter_property winSizeY TYPE INTEGER
set_parameter_property winSizeY UNITS None
set_parameter_property winSizeY ALLOWED_RANGES -2147483648:2147483647
set_parameter_property winSizeY HDL_PARAMETER true
add_parameter blockSizeX INTEGER 7
set_parameter_property blockSizeX DEFAULT_VALUE 7
set_parameter_property blockSizeX DISPLAY_NAME blockSizeX
set_parameter_property blockSizeX TYPE INTEGER
set_parameter_property blockSizeX UNITS None
set_parameter_property blockSizeX ALLOWED_RANGES -2147483648:2147483647
set_parameter_property blockSizeX HDL_PARAMETER true
add_parameter blockSizeY INTEGER 7
set_parameter_property blockSizeY DEFAULT_VALUE 7
set_parameter_property blockSizeY DISPLAY_NAME blockSizeY
set_parameter_property blockSizeY TYPE INTEGER
set_parameter_property blockSizeY UNITS None
set_parameter_property blockSizeY ALLOWED_RANGES -2147483648:2147483647
set_parameter_property blockSizeY HDL_PARAMETER true
add_parameter strideX INTEGER 1
set_parameter_property strideX DEFAULT_VALUE 1
set_parameter_property strideX DISPLAY_NAME strideX
set_parameter_property strideX TYPE INTEGER
set_parameter_property strideX UNITS None
set_parameter_property strideX ALLOWED_RANGES -2147483648:2147483647
set_parameter_property strideX HDL_PARAMETER true
add_parameter strideY INTEGER 1
set_parameter_property strideY DEFAULT_VALUE 1
set_parameter_property strideY DISPLAY_NAME strideY
set_parameter_property strideY TYPE INTEGER
set_parameter_property strideY UNITS None
set_parameter_property strideY ALLOWED_RANGES -2147483648:2147483647
set_parameter_property strideY HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 slave_addr address Input 4
add_interface_port avalon_slave_0 slave_rd_en read Input 1
add_interface_port avalon_slave_0 slave_wr_en write Input 1
add_interface_port avalon_slave_0 slave_readdata readdata Output 32
add_interface_port avalon_slave_0 slave_writedata writedata Input 32
add_interface_port avalon_slave_0 slave_waitrequest waitrequest Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 0
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_addr address Output 32
add_interface_port avalon_master master_rd_en read Output 1
add_interface_port avalon_master master_wr_en write Output 1
add_interface_port avalon_master master_be byteenable Output 2
add_interface_port avalon_master master_readdata readdata Input 16
add_interface_port avalon_master master_writedata writedata Output 16
add_interface_port avalon_master master_waitrequest waitrequest Input 1

