#!/bin/bash

# Runs our java project
# Don't forget to give privileges: chmod 755 run

if [ $# -eq 0 ]; then
    java -cp .:../pi4j/* force/pi/Magic
elif [ "$1" = 'connector' ]; then
    java -cp .:../pi4j/* force/pi/connector/Main
else
    echo "Invalid usage"
fi
